version: '3.8'

services:
  web:
    build: .
    ports:
      - "8082:8000"
    volumes:
      - ./data:/app/data
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    restart: unless-stopped
